# Generated by Django 6.0.2 on 2026-02-22 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('amount_lost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damaged_items', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('police_intervention', models.BooleanField(default=False)),
                ('injured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='branches.branch')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incident_date', '-incident_time'],
            },
        ),
    ]
