# Generated by Django 6.0.2 on 2026-02-21 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out')], max_length=10)),
                ('captured_time', models.CharField(blank=True, default='', help_text='Time extracted from OCR (HH:MM or HH:MM:SS)', max_length=20)),
                ('captured_branch', models.CharField(blank=True, default='', help_text='Branch/location name extracted from OCR', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Photo captured from the attendance terminal', null=True, upload_to='attendance/%Y/%m/')),
                ('method', models.CharField(choices=[('camera', 'Camera'), ('manual', 'Manual')], default='camera', max_length=10)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for manual attendance request')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='attendance__user_id_8b36c6_idx'), models.Index(fields=['branch', '-created_at'], name='attendance__branch__29fb16_idx'), models.Index(fields=['type'], name='attendance__type_4a846a_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
            },
        ),
    ]
