# Generated by Django 6.0.2 on 2026-02-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostershift',
            name='break_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Unpaid break in minutes'),
        ),
        migrations.AddField(
            model_name='rostershift',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate ($)', max_digits=8),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='break_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Unpaid break duration in minutes'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default hourly rate ($)', max_digits=8),
        ),
    ]
