# Generated by Django 6.0.2 on 2026-02-22 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rostershift_break_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Remove old unique_together first (references day_of_week)
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        # 2. Remove old field
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        # 3. Add new fields
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default='2026-01-01', help_text='Specific date for availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='availability',
            name='preset',
            field=models.CharField(choices=[('whole_day', 'Whole Day'), ('day_only', 'Day Only'), ('night_only', 'Night Only'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True, help_text='False = explicitly unavailable / day off'),
        ),
        # 4. Set new unique_together and options
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('user', 'date')},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'user', 'start_time'], 'verbose_name_plural': 'Availabilities'},
        ),
    ]
