# Generated by Django 6.0.2 on 2026-02-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='preset',
            field=models.CharField(choices=[('whole_day', 'Whole Day'), ('day_only', 'Day Only'), ('night_only', 'Night Only'), ('from_time', 'From Time'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
