# Generated by Django 6.0.2 on 2026-02-18 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='branches.branch')),
            ],
            options={
                'ordering': ['branch__company__name', 'branch__name', 'area_name'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='qr_codes.qrcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['branch', 'area_name'], name='qr_codes_qr_branch__e9f152_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['status'], name='qr_codes_qr_status_0637df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together={('branch', 'area_name')},
        ),
        migrations.AddIndex(
            model_name='qrcodesubmission',
            index=models.Index(fields=['qr_code', '-scanned_at'], name='qr_codes_qr_qr_code_d7d5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodesubmission',
            index=models.Index(fields=['user', '-scanned_at'], name='qr_codes_qr_user_id_5fe218_idx'),
        ),
    ]
