# Generated by Django 6.0.2 on 2026-02-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('profiles', '0002_alter_profile_photo_profileaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_branches',
            field=models.ManyToManyField(blank=True, help_text='Branches this user prefers to work at.', related_name='preferred_by', to='branches.branch'),
        ),
    ]
